/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#f4f4f5",
        "primary": "#005DAA",
        "primary-hover": "#004580",
        "primary-light": "#F0F7FF",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e4e4e7",
        "primary-fixed": "#F0F7FF",
        "on-background": "#09090b",
        "on-error": "#ffffff",
        "status-docked": "#BAE6FD",
        "surface-tint": "#005DAA",
        "on-tertiary-container": "#005DAA",
        "error": "#dc2626",
        "secondary-container": "#27272a",
        "on-error-container": "#7f1d1d",
        "on-surface": "#09090b",
        "on-surface-variant": "#52525b",
        "glass-border": "rgba(228, 228, 231, 0.8)",
        "outline": "#52525b",
        "outline-variant": "#e4e4e7",
        "primary-container": "#F0F7FF",
        "inverse-primary": "#E0F2FE",
        "on-primary-fixed": "#002B49",
        "tertiary-container": "#f4f4f5",
        "surface-variant": "#f4f4f5",
        "primary-fixed-dim": "#BAE6FD",
        "surface": "#ffffff",
        "dark-panel": "#18181b",
        "surface-bright": "#ffffff",
        "inverse-surface": "#18181b",
        "on-secondary-fixed": "#18181b",
        "background": "#ffffff",
        "tertiary-fixed-dim": "#e4e4e7",
        "on-primary-container": "#003366",
        "inverse-on-surface": "#fafafa",
        "on-tertiary-fixed": "#18181b",
        "glass-surface": "rgba(255, 255, 255, 0.95)",
        "surface-container-high": "#f4f4f5",
        "tertiary-fixed": "#f4f4f5",
        "on-tertiary-fixed-variant": "#52525b",
        "tertiary": "#71717a",
        "on-primary-fixed-variant": "#004580",
        "surface-container": "#fafafa",
        "on-secondary-container": "#ffffff",
        "status-delayed": "#fee2e2",
        "on-secondary-fixed-variant": "#27272a",
        "on-secondary": "#ffffff",
        "status-transit": "#E0F2FE",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e4e4e7",
        "error-container": "#fee2e2",
        "secondary": "#18181b",
        "surface-container-low": "#fafafa",
        "secondary-fixed": "#f4f4f5",
        "surface-container-lowest": "#ffffff",
        bocs: {
          blue: '#005DAA',
          blueDark: '#002B49',
          blueLight: '#F0F7FF',
          green: '#00875A',
          greenDark: '#006E48',
          greenLight: '#ECFDF5',
          navy: '#071D33',
          black: '#09090b',
          dark: '#18181b',
          grayText: '#52525b',
          grayBg: '#fafafa',
          border: '#e4e4e7',
          white: '#ffffff',
        }
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1440px",
        "unit": "4px",
        "gutter": "24px",
        "sidebar-width": "260px"
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        heading: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      }
    },
  },
  plugins: [],
}
